# Generated by Django 5.1.6 on 2026-06-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('completado', 'Completado')], default='activo', max_length=20, verbose_name='Estado')),
                ('tiene_acompanante', models.BooleanField(default=False, verbose_name='¿Tiene acompañante?')),
                ('acompanante_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del acompañante')),
                ('acompanante_telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del acompañante')),
                ('acompanante_parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco')),
                ('material_entregado', models.CharField(choices=[('dvd', 'DVD'), ('pendrive', 'Pendrive'), ('ninguno', 'No entregado')], default='ninguno', max_length=20, verbose_name='Material entregado')),
                ('kinesiologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kinesiólogo asignado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la nota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('es_urgente', models.BooleanField(default=False, verbose_name='¿Es urgente?')),
                ('kinesiologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kinesiólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='kinesiologo.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la rutina')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ejercicios', models.TextField(verbose_name='Ejercicios (descripción detallada)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL del video')),
                ('duracion_minutos', models.IntegerField(default=30, verbose_name='Duración (minutos)')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('lunes_miercoles_viernes', 'Lunes, Miércoles y Viernes'), ('martes_jueves', 'Martes y Jueves'), ('personalizada', 'Personalizada')], default='diaria', max_length=50, verbose_name='Frecuencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('pausada', 'Pausada')], default='activa', max_length=20, verbose_name='Estado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='kinesiologo.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de seguimiento')),
                ('cumple_ejercicios', models.BooleanField(default=False, verbose_name='¿Cumplió los ejercicios?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tipo_control', models.CharField(choices=[('presencial', 'Control presencial'), ('telefonico', 'Control telefónico'), ('whatsapp', 'Vía WhatsApp'), ('cartilla', 'Revisión de cartilla')], default='presencial', max_length=20, verbose_name='Tipo de control')),
                ('acompanante_presente', models.BooleanField(default=False, verbose_name='¿Acompañante presente?')),
                ('fecha_proximo_control', models.DateField(blank=True, null=True, verbose_name='Próximo control')),
                ('kinesiologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kinesiólogo que realizó el seguimiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='kinesiologo.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
